version: '3'

volumes:
  pg_data2:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data2:/var/lib/postgresql/data
  backend:
    image: zhukov1414/kittygram_backend
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media/cats/images/
  frontend:
    image: zhukov1414/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: zhukov1414/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/media/cats/images/
    ports:
      - 9000:80

